### ISSUE TITLE
[Docs]: typo in readme

### ISSUE THREAD

**Issue by shijiadong2022** [fidelity/theliv#232]
Documentation link: https://github.com/fidelity/theliv/blob/main/readme.md 

Description: 
While an developer can perfectly be equipped with the necessary skills to debug using the above flow, most of the time they dont want to do it since their focus is on rolling out a business feature to production asap.

Change dont to don't

**Comment by ravin-shah** [comment]
will work on it shortly

**Comment by towens182** [comment]
@ravin-shah May I address this issue now?

**Comment by ravin-shah** [comment]
@towens182 Sure, go ahead.
