### ISSUE TITLE
[Docs] typo in readme

### ISSUE THREAD

**Issue by shijiadong2022** [fidelity/theliv#234]
documentation link: https://github.com/fidelity/theliv/blob/main/readme.md

Description:
E.g Mutiple factors could come into play in a specific issue

**Comment by ramshankarb** [comment]
will work on it shortly

**Comment by towens182** [comment]
@ramshankarb May I address this issue now?

**Comment by ramshankarb** [comment]
> @ramshankarb May I address this issue now?

Sure.
